### ISSUE TITLE
Add this to UMEP for Processing

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/umep-reqs#2]
So how do we actually add this into the plugin? We already have supyinstaller and now we will have two installers?

**Comment by biglimp** [comment]
But then we need to add the dependencies for SuPy in umep-reqs or...?

**Comment by sunt05** [comment]
Everything needed by UMEP can be handled by `umep-reqs`

**Comment by biglimp** [comment]
Py?So just add all Supy recs into umep recs? What if you change reqs for SuPy?

**Comment by sunt05** [comment]
SuPy reqs are looked after by SuPy  itself - as long as `supy` is included in `umep-reqs`, one doesn't need to explicit outline everything under `supy` - similar for other dependencies.

**Comment by biglimp** [comment]
aha, so we add supy as a reqs in umep-reqs...

**Comment by biglimp** [comment]
Thanks for the chat Ting. Now I get it. I will change in UMEP. @j3r3m1 , can you add the packages needed into umep-reqs please.
One more question: how can I add the "--use-feature=2020-resolver" switch when installing supy?

**Comment by sunt05** [comment]
Just leave that option as is.

**Comment by biglimp** [comment]
Then supy dependecy needs to be outside umep-reqs or how do I write this in https://github.com/UMEP-dev/umep-reqs/blob/2c27f63ef135c730817488d4bdcd6f229ffa18fe/umep-reqs/setup.py#L30?

**Comment by sunt05** [comment]
I suppose you are working on these lines:

https://github.com/UMEP-dev/UMEP-processing/blob/91104db86978384128faf5777e58b5820c337cf7/util/supy_installer.py#L76-L81

just replace `supy` with `umep-reqs` should do the job:

https://github.com/UMEP-dev/UMEP-processing/blob/91104db86978384128faf5777e58b5820c337cf7/util/supy_installer.py#L81

`--use-feature=2020-resolver` is an option for `pip` and should be kept as is now.

**Comment by j3r3m1** [comment]
> Thanks for the chat Ting. Now I get it. I will change in UMEP. @j3r3m1 , can you add the packages needed into umep-reqs please. 

I currently have numba=0.56.4, netcdf4=1.6.2 and jaydebeapi=1.2.3. @biglimp do you have the same versions ?

**Comment by biglimp** [comment]
numba                         0.56.4
netCDF4                       1.6.1
JayDeBeApi                    1.2.3

**Comment by j3r3m1** [comment]
Took your and updated in #3. Single comment, I made a modification in the gitignore that was proposed by Spyder but not sure it is relevant.

**Comment by j3r3m1** [comment]
Well it seems the deploy fails due to a Token problem. I have accepted to be maintainer of the project in Pypi and created a new token on Pypi that starts with pypi and has token as username. This token is same on my home in a file called .pypirc. The error remains anyway. Any idea where does this come from ?

**Comment by biglimp** [comment]
no idea. @sunt05 ?

**Comment by sunt05** [comment]
no need to do any deployment locally - this repo is set up to deploy new version to pypi via GitHub Actions.
for new version, just tag the commit for release - that should do all the job.

**Comment by j3r3m1** [comment]
It was not local test but GitHub action that tries the deployment in my PullRequest. I have merged, let's see what's going on.

**Comment by sunt05** [comment]
I see - I'll need to add you @j3r3m1 and @biglimp to the test pypi as owners as well - will do it now.

**Comment by sunt05** [comment]
sorry - @j3r3m1 and @biglimp please also sign up here: https://test.pypi.org/

**Comment by j3r3m1** [comment]
done: https://test.pypi.org/user/J3r3m1/

**Comment by j3r3m1** [comment]
Cool thanks I suppose it should work if I resubmitt a PR now. Let's try later
